version: '3.4'

services:
  bemarketplace:
    image: bemarketplace
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
